name: build and test
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: npm install
        run: npm install

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t sebastianabril6/social-wires-backend:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Pusk Docker Image
        run: docker push sebastianabril6/social-wires-backend:latest

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: deploy to AWS EC2
        uses: appleboy/shh-action@master
        with:
          host: ${{}}
          username: ${{}}
          key: ${{}}
          script: docker rm -f trips-api || true
            docker run -d --pull always --restart always --name trips-api --net trip-net -p 3000:3000 -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} -e DATABASE_PORT=${{ secrets.DATABASE_PORT }} -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} -e DATABASE_NAME=${{ secrets.DATABASE_NAME }} sebastianabril6/trips-api:latest
